
FROM node:10

WORKDIR /usr/src/app

#COPY package*.json ./
#COPY package.json /usr/src/app/react_front
#COPY ./full/react_front /usr/src/app
#RUN npm install
ADD ./full/react_front/package.json /usr/src/app/package.json
ADD ./full/react_front /usr/src/app
CMD npm install && npm run start
#CMD ["npm", "run", "start"]
EXPOSE 3000




# FROM node:10-alpine

# ARG NODE_ENV=development
# ENV NODE_ENV=${NODE_ENV}

# WORKDIR /usr/src/app

# COPY package*.json ./
# ADD package.json /usr/src/app/package.json
# RUN npm install

# COPY . .
# ADD . /usr/src/app
# RUN chmod 755 /usr/src/app

# CMD [ "npm", "start" ]